name: Python Application Test

on: [push]

jobs:
  test-application:
    name: Run Application Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here



    - name: Test with 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt test2_output.txt
        # Debugging: Print the output file's contents
        echo "Output of the script:"
        cat test2_output.txt
        echo "End of output file"
        # Post-process output to convert float to int if applicable
        awk '{if ($1 == int($1)) print int($1); else print $1;}' test2_output.txt > temp.txt && mv temp.txt test2_output.txt
        # Compare the output with the expected result
        diff test2_output.txt test_data/test2_expected.txt

    - name: Test blank file
      run: |
        python find_lowest_number.py test_data/test3_input.txt test3_output.txt
        # Debugging: Print the output file's contents
        echo "Output of the script:"
        cat test3_output.txt
        echo "End of output file"
        # Compare the output with the expected result
        diff test3_output.txt test_data/test3_expected.txt
