
name: Python Application Test

on: [push]

jobs:
  test-application:
    name: Run Application Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here

    - name: Test with 10 numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt test1_output.txt
        # Output the result for manual verification
        cat test1_output.txt
        # If the workflow should fail if the output is not as expected, you would add that check here

    - name: Test with 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt test2_output.txt
        # Output the result for manual verification
        cat test2_output.txt
        # If the workflow should fail if the output is not as expected, you would add that check here

    - name: Test blank file
      run: |
        python find_lowest_number.py test_data/test3_input.txt test3_output.txt
        # Output the result for manual verification
        cat test3_output.txt
        # If the workflow should fail if the output is not as expected, you would add that check here
